#!/bin/bash

PROG=aletrader
PORT=8080
LIB_DIR=/opt/$PROG

. /etc/init.d/functions

JAVA_OPTS="-D$PROG $JAVA_OPTS -server"
CLASSPATH=$( echo $LIB_DIR/WEB-INF/lib/*.jar . | sed 's/ /:/g'):$LIB_DIR/WEB-INF/classes

CMD="java $JAVA_OPTS -classpath $CLASSPATH com.aletrader.Server $PORT / $LIB_DIR"

export PIDFILE=/var/run/$PROG.pid

start() {
  ulimit -n 50000
  if [ -f $PIDFILE ]; then
    status -p $PIDFILE &> /dev/null
    if [ $? == 0 ]; then
      failure
      echo
      exit 1
    fi
  fi
  daemon --pidfile=$PIDFILE "$CMD &"
  ps aux | grep "$LIB_DIR" | grep -v grep | awk '{print $2}' > $PIDFILE
  echo $PROG started
}

stop() {
  killproc -p $PIDFILE -2
  echo $PROG stopped
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  status)
    status -p $PIDFILE
  ;;
  restart)
    stop
    start
  ;;
*)
echo $"Usage: $0 {start|stop|restart|status}"
exit 1
esac
exit 0
